var company = "Facebook";

var items = [
    {
        "id": 461,
        "title": "Hamming Distance",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    },
    {
        "id": 637,
        "title": "Average of Levels in Binary Tree",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    },
    {
        "id": 283,
        "title": "Move Zeroes",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    },
    {
        "id": 653,
        "title": "Two Sum IV - Input is a BST",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    },
    {
        "id": 252,
        "title": "Meeting Rooms",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    },
    {
        "id": 404,
        "title": "Sum of Left Leaves",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    },
    {
        "id": 13,
        "title": "Roman to Integer",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    },
    {
        "id": 206,
        "title": "Reverse Linked List",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    },
    {
        "id": 543,
        "title": "Diameter of Binary Tree",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    },
    {
        "id": 674,
        "title": "Longest Continuous Increasing Subsequence",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    },
    {
        "id": 121,
        "title": "Best Time to Buy and Sell Stock",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    },
    {
        "id": 572,
        "title": "Subtree of Another Tree",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    },
    {
        "id": 257,
        "title": "Binary Tree Paths",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    },
    {
        "id": 235,
        "title": "Lowest Common Ancestor of a Binary Search Tree",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    },
    {
        "id": 597,
        "title": "Friend Requests I: Overall Acceptance Rate",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    },
    {
        "id": 1,
        "title": "Two Sum",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    },
    {
        "id": 38,
        "title": "Count and Say",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    },
    {
        "id": 26,
        "title": "Remove Duplicates from Sorted Array",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    },
    {
        "id": 20,
        "title": "Valid Parentheses",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    },
    {
        "id": 67,
        "title": "Add Binary",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    },
    {
        "id": 234,
        "title": "Palindrome Linked List",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    },
    {
        "id": 680,
        "title": "Valid Palindrome II",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    },
    {
        "id": 88,
        "title": "Merge Sorted Array",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    },
    {
        "id": 157,
        "title": "Read N Characters Given Read4",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    },
    {
        "id": 28,
        "title": "Implement strStr()",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    },
    {
        "id": 69,
        "title": "Sqrt(x)",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    },
    {
        "id": 168,
        "title": "Excel Sheet Column Title",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    },
    {
        "id": 125,
        "title": "Valid Palindrome",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    },
    {
        "id": 278,
        "title": "First Bad Version",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    },
    {
        "id": 535,
        "title": "Encode and Decode TinyURL",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 647,
        "title": "Palindromic Substrings",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 311,
        "title": "Sparse Matrix Multiplication",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 238,
        "title": "Product of Array Except Self",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 477,
        "title": "Total Hamming Distance",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 554,
        "title": "Brick Wall",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 286,
        "title": "Walls and Gates",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 398,
        "title": "Random Pick Index",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 636,
        "title": "Exclusive Time of Functions",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 494,
        "title": "Target Sum",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 325,
        "title": "Maximum Size Subarray Sum Equals k",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 78,
        "title": "Subsets",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 173,
        "title": "Binary Search Tree Iterator",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 621,
        "title": "Task Scheduler",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 377,
        "title": "Combination Sum IV",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 341,
        "title": "Flatten Nested List Iterator",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 602,
        "title": "Friend Requests II: Who Has the Most Friends",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 714,
        "title": "Best Time to Buy and Sell Stock with Transaction Fee",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 102,
        "title": "Binary Tree Level Order Traversal",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 525,
        "title": "Contiguous Array",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 215,
        "title": "Kth Largest Element in an Array",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 334,
        "title": "Increasing Triplet Subsequence",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 750,
        "title": "Number Of Corner Rectangles",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 380,
        "title": "Insert Delete GetRandom O(1)",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 253,
        "title": "Meeting Rooms II",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 75,
        "title": "Sort Colors",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 670,
        "title": "Maximum Swap",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 261,
        "title": "Graph Valid Tree",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 314,
        "title": "Binary Tree Vertical Order Traversal",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 90,
        "title": "Subsets II",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 49,
        "title": "Group Anagrams",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 80,
        "title": "Remove Duplicates from Sorted Array II",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 285,
        "title": "Inorder Successor in BST",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 200,
        "title": "Number of Islands",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 277,
        "title": "Find the Celebrity",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 17,
        "title": "Letter Combinations of a Phone Number",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 275,
        "title": "H-Index II",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 117,
        "title": "Populating Next Right Pointers in Each Node II",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 274,
        "title": "H-Index",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 33,
        "title": "Search in Rotated Sorted Array",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 161,
        "title": "One Edit Distance",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 209,
        "title": "Minimum Size Subarray Sum",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 673,
        "title": "Number of Longest Increasing Subsequence",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 56,
        "title": "Merge Intervals",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 139,
        "title": "Word Break",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 721,
        "title": "Accounts Merge",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 236,
        "title": "Lowest Common Ancestor of a Binary Tree",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 208,
        "title": "Implement Trie (Prefix Tree)",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 221,
        "title": "Maximal Square",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 210,
        "title": "Course Schedule II",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 578,
        "title": "Get Highest Answer Rate Question",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 43,
        "title": "Multiply Strings",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 79,
        "title": "Word Search",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 50,
        "title": "Pow(x, n)",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 71,
        "title": "Simplify Path",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 133,
        "title": "Clone Graph",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 211,
        "title": "Add and Search Word - Data structure design",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 98,
        "title": "Validate Binary Search Tree",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 523,
        "title": "Continuous Subarray Sum",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 15,
        "title": "3Sum",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 91,
        "title": "Decode Ways",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 127,
        "title": "Word Ladder",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 534,
        "title": "Design TinyURL",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 689,
        "title": "Maximum Sum of 3 Non-Overlapping Subarrays",
        "difficulty": "Hard",
        "done": 0,
        "description": "",
    },
    {
        "id": 410,
        "title": "Split Array Largest Sum",
        "difficulty": "Hard",
        "done": 0,
        "description": "",
    },
    {
        "id": 265,
        "title": "Paint House II",
        "difficulty": "Hard",
        "done": 0,
        "description": "",
    },
    {
        "id": 128,
        "title": "Longest Consecutive Sequence",
        "difficulty": "Hard",
        "done": 0,
        "description": "",
    },
    {
        "id": 301,
        "title": "Remove Invalid Parentheses",
        "difficulty": "Hard",
        "done": 0,
        "description": "",
    },
    {
        "id": 297,
        "title": "Serialize and Deserialize Binary Tree",
        "difficulty": "Hard",
        "done": 0,
        "description": "",
    },
    {
        "id": 25,
        "title": "Reverse Nodes in k-Group",
        "difficulty": "Hard",
        "done": 0,
        "description": "",
    },
    {
        "id": 642,
        "title": "Design Search Autocomplete System",
        "difficulty": "Hard",
        "done": 0,
        "description": "",
    },
    {
        "id": 282,
        "title": "Expression Add Operators",
        "difficulty": "Hard",
        "done": 0,
        "description": "",
    },
    {
        "id": 85,
        "title": "Maximal Rectangle",
        "difficulty": "Hard",
        "done": 0,
        "description": "",
    },
    {
        "id": 57,
        "title": "Insert Interval",
        "difficulty": "Hard",
        "done": 0,
        "description": "",
    },
    {
        "id": 218,
        "title": "The Skyline Problem",
        "difficulty": "Hard",
        "done": 0,
        "description": "",
    },
    {
        "id": 23,
        "title": "Merge k Sorted Lists",
        "difficulty": "Hard",
        "done": 0,
        "description": "",
    },
    {
        "id": 76,
        "title": "Minimum Window Substring",
        "difficulty": "Hard",
        "done": 0,
        "description": "",
    },
    {
        "id": 269,
        "title": "Alien Dictionary",
        "difficulty": "Hard",
        "done": 0,
        "description": "",
    },
    {
        "id": 158,
        "title": "Read N Characters Given Read4 II - Call multiple times",
        "difficulty": "Hard",
        "done": 0,
        "description": "",
    },
    {
        "id": 639,
        "title": "Decode Ways II",
        "difficulty": "Hard",
        "done": 0,
        "description": "",
    },
    {
        "id": 10,
        "title": "Regular Expression Matching",
        "difficulty": "Hard",
        "done": 0,
        "description": "",
    },
    {
        "id": 273,
        "title": "Integer to English Words",
        "difficulty": "Hard",
        "done": 0,
        "description": "",
    },
    {
        "id": 44,
        "title": "Wildcard Matching",
        "difficulty": "Hard",
        "done": 0,
        "description": "",
    },
    {
        "id": 745,
        "title": "Prefix and Suffix Search",
        "difficulty": "Hard",
        "done": 0,
        "description": "",
    },
    {
        "id": 68,
        "title": "Text Justification",
        "difficulty": "Hard",
        "done": 0,
        "description": "",
    },
    {
        "id": 146,
        "title": "LRU Cache",
        "difficulty": "Hard",
        "done": 0,
        "description": "",
    }
];