var company = "Uber";

var items = [
    {
        "id": 10,
        "title": "Regular Expression Matching",
        "difficulty": "Hard",
        "done": 0,
        "description": "",
    },
    {
        "id": 76,
        "title": "Minimum Window Substring",
        "difficulty": "Hard",
        "done": 0,
        "description": "",
    },
    {
        "id": 291,
        "title": "Word Pattern II ",
        "difficulty": "Hard",
        "done": 0,
        "description": "",
    },
    {
        "id": 297,
        "title": "Serialize and Deserialize Binary Tree",
        "difficulty": "Hard",
        "done": 0,
        "description": "",
    },
    {
        "id": 146,
        "title": "LRU Cache",
        "difficulty": "Hard",
        "done": 0,
        "description": "",
    },
    {
        "id": 432,
        "title": "All O`one Data Structure",
        "difficulty": "Hard",
        "done": 0,
        "description": "",
    },
    {
        "id": 262,
        "title": "Trips and Users",
        "difficulty": "Hard",
        "done": 0,
        "description": "",
    },
    {
        "id": 699,
        "title": "Falling Squares",
        "difficulty": "Hard",
        "done": 0,
        "description": "",
    },
    {
        "id": 37,
        "title": "Sudoku Solver",
        "difficulty": "Hard",
        "done": 0,
        "description": "",
    },
    {
        "id": 140,
        "title": "Word Break II",
        "difficulty": "Hard",
        "done": 0,
        "description": "",
    },
    {
        "id": 23,
        "title": "Merge k Sorted Lists",
        "difficulty": "Hard",
        "done": 0,
        "description": "",
    },
    {
        "id": 39,
        "title": "Combination Sum",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 17,
        "title": "Letter Combinations of a Phone Number",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 49,
        "title": "Group Anagrams",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 648,
        "title": "Replace Words",
        "difficulty": "Medium",
        "done": 1,
        "description": "Trie 存所有的root"
    },
    {
        "id": 249,
        "title": "Group Shifted Strings ",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 22,
        "title": "Generate Parentheses",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 54,
        "title": "Spiral Matrix",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 133,
        "title": "Clone Graph",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 534,
        "title": "Design TinyURL",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 8,
        "title": "String to Integer (atoi)",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 535,
        "title": "Encode and Decode TinyURL",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 636,
        "title": "Exclusive Time of Functions",
        "difficulty": "Medium",
        "done": 1,
        "again": 1,
        "description": "stack 存之前剩下的fid, 记录上一个开始时间preime\n" +
                       "如果新遇到log是start, stack.peek的时间加上time - preTime, preTime = time\n" +
                       "如果新遇到log是end, stack.peek的时间加上time - preTime + 1, preTime = time + 1 (因为time是end time)",
    },
    {
        "id": 450,
        "title": "Delete Node in a BST",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 208,
        "title": "Implement Trie (Prefix Tree)",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 186,
        "title": "Reverse Words in a String II ",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 139,
        "title": "Word Break",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 254,
        "title": "Factor Combinations ",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 380,
        "title": "Insert Delete GetRandom O(1)",
        "difficulty": "Medium",
        "done": 1,
        "description": "ArrayList, and Map -(key is number, value is its index in array).\n"
                       + "When Insert, add to list end. When remove, move the number to list end, remove from end.",
    },
    {
        "id": 138,
        "title": "Copy List with Random Pointer",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 36,
        "title": "Valid Sudoku",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 207,
        "title": "Course Schedule",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 230,
        "title": "Kth Smallest Element in a BST",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 33,
        "title": "Search in Rotated Sorted Array",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 516,
        "title": "Longest Palindromic Subsequence",
        "difficulty": "Medium",
        "done": 1,
        "again": 1,
        "description": "dp[i][j]: the longest palindromic subsequence's length of substring(i, j)\n"
                       + "dp[i][j] = dp[i+1][j-1] + 2 if s.charAt(i) == s.charAt(j)\n"
                       + "otherwise, dp[i][j] = Math.max(dp[i+1][j], dp[i][j-1])",
    },
    {
        "id": 91,
        "title": "Decode Ways",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 78,
        "title": "Subsets",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 337,
        "title": "House Robber III",
        "difficulty": "Medium",
        "done": 1,
        "description": "从上往下递归，每个点算偷这个点的钱 include，和不偷这个点的钱 exclude\n"
                       + "不改变TreeNode结构的话，就返回int[2], res[0] = include, res[1]=exlude \n"
                       + "每个点 include = left exclude + right exclude + this.val \n"
                       + "exclude = max(left include, left exclude) + max(right include, right exclude)",
    },
    {
        "id": 161,
        "title": "One Edit Distance ",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 373,
        "title": "Find K Pairs with Smallest Sums",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 692,
        "title": "Top K Frequent Words",
        "difficulty": "Medium",
        "done": 1,
        "description": "map存word count，minHeap存前k个most frequency word"
    },
    {
        "id": 24,
        "title": "Swap Nodes in Pairs",
        "difficulty": "Medium",
        "done": 0,
        "description": "",
    },
    {
        "id": 735,
        "title": "Asteroid Collision",
        "difficulty": "Medium",
        "done": 1,
        "description": "从左往右扫，左边扫完地放stack里，右边新元素跟stack.peek() 比较。\n"
                       + "只有stack.peek>0 (向右移) && 新元素<0（向左移）才有可能碰撞",
    },
    {
        "id": 202,
        "title": "Happy Number",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    },
    {
        "id": 155,
        "title": "Min Stack",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    },
    {
        "id": 121,
        "title": "Best Time to Buy and Sell Stock",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    },
    {
        "id": 125,
        "title": "Valid Palindrome",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    },
    {
        "id": 242,
        "title": "Valid Anagram",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    },
    {
        "id": 266,
        "title": "Palindrome Permutation ",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    },
    {
        "id": 206,
        "title": "Reverse Linked List",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    },
    {
        "id": 104,
        "title": "Maximum Depth of Binary Tree",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    },
    {
        "id": 171,
        "title": "Excel Sheet Column Number",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    },
    {
        "id": 1,
        "title": "Two Sum",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    },
    {
        "id": 690,
        "title": "Employee Importance",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    },
    {
        "id": 13,
        "title": "Roman to Integer",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    },
    {
        "id": 290,
        "title": "Word Pattern",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    },
    {
        "id": 733,
        "title": "Flood Fill",
        "difficulty": "Easy",
        "done": 0,
        "description": "",
    }
];